config/routes.rb
GimmeSupport::Application.routes.draw do

  get "suggestions/new"

  get "suggestions/show"

  get "suggestions/edit"

  get "chats/new"

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  get "questions/new"

  get "questions/edit"

  get "questions/show"

  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'

  resources :members
  resources :communities do
    resources :questions
    resources :suggestions
  end
  resources :questions do
    resources :responses
    resources :suggestions
  end
  resources :responses
  resources :suggestions
  resources :chats

  get "communities/search"
  post "communities/find"
  match "communities/search" => "communities#search"

   root :to => 'pages#home'

end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :questions, :dependent => :destroy
  has_many :suggestions, :dependent => :destroy
  has_and_belongs_to_many :members

  has_attached_file :logo, :styles => {:medium => "300 * 300>", 
                        :thumb => "100* 100>"}

  validates :name, :presence => true
  validates :name, :uniqueness => true
  validates_attachment_presence :logo
  validates_attachment_size :logo, :less_than => 1.megabytes
  validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']

  scope :find_company, where(:conditions =>[ "lower(name) = ?", name.downcase ]) 

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index

  end

  def new
    @community = Community.new

  end

  def create

    params[:community][:name]= params[:community][:name].downcase #change casing to lower case before save. 
    @community = Community.new(params[:community])
    if @community.save
      flash[:success] = "New Support Community Successfully created, #{@community.name}"
      redirect_to @community
    else
      flash[:error] = "Process unsuccessful"
      @title = "New community"
      render 'new'
    end

  end

  def show
    @community = Community.find(params[:id])
    @questions = @community.questions
    @questions = @questions.paginate(:page=>params[:page], :per_page => 5)
    @suggestions = @community.suggestions.paginate(:page=>params[:page], :per_page => 5)
    @members = @community.members
    #@questions = @community.questions.blank?[] : @community.questions
    #@community = Community.find_by_name(params[:id]) #for displaying url with company name 
      respond_to do |format|
        format.html
        format.js
      end
  end

  def edit
    @community = Community.find(params[:id])

  end

  def update

    @community = Community.find(params[:id])
    params[:community][:name]= params[:community][:name].downcase #change casing to lower case before save. 
    if @community.update_attributes(params[:community])
      flash[:success] = "Community updated successfully"
      redirect_to @community

    else
      flash[:notic] = "Oops something went wrong"
      @title = Edit Community
      render "edit"
    end
  end

  def chat
    render :controller => "chats", :action => "index"

  end
  
  def find

    if params[:companyname]
     @community = Community.find_by_name(params[:companyname].downcase) 
     unless @community.nil?
       redirect_to @community
     else
       flash[:notice] = "Company not found"
       #redirect_to "index"
       render "index"
      end
    end
  end

end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%#multipart enables the file uploading and validates implements the client-side-validation functionality%> 
<%=form_for(@community, :html => { :multipart => true }, :validate => true) do |f| %>
  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.submit "Create Community" %>
  </div>

<% end %>

app/views/communities/_questions.html.erb
<%#<%= render @questions unless @questions.empty? %>

<% unless @questions.blank? -%>
  <% @questions.each do |question| -%>
    <div class="postedby"><p><%= link_to question.member.user_name unless question.member.blank?%></p></div>
    <div class="thumbimage"><%= image_tag question.member.avatar.url("small") unless question.member.blank?%></div>
    <div class="questiontext"><p><%=link_to question.content, community_question_path(question.community, question) %></p></div>
    <div class="time"><%="#{time_ago_in_words question.created_at} ago"  %></div>
    <div class="responses"><%= pluralize question.responses.count, "response" %></div>
    <div class="status"><%= question.status %></div>
    <hr/>
  <% end -%>
<% end -%>
<%#pagination functionality for questions displayed%> 
<%= will_paginate @questions %>

app/views/communities/edit.html.erb
<h1>Communities#edit</h1>
<p>Find me in app/views/communities/edit.html.erb</p>

<%= render "form" %>

app/views/communities/index.html.erb
<p>this is index for communities</p>

app/views/communities/new.html.erb
<h1>Communities#new</h1>
<%= render "form" %>
<p>Find me in app/views/communities/new.html.erb</p>

app/views/communities/show.html.erb
<div id="page">
  <div id="content">
    <div class="post">

      <script>
        jQuery(function(){
          jQuery(".tabnav").tabs();
        });
      </script>
      
      <div id="tabs">

        <ul class="tabnav">
          <li ><%= link_to "Ask a question", "#question_form", :id=>"active-tab" %></li>
          <li><%= link_to "Post a suggestion", "#suggestion_form" %></li>
        </ul>
        <div class= "panes">
          <div id="question_form" class="tabdiv">
            <%#currently the first member of the community is doing all the questions. TODO: Change this behaviour%>
            <%= form_for @community.questions.build(:member_id => Member.last.id), :remote => true do |f|%>

              <%= f.hidden_field :member_id %>
              <%= f.hidden_field :community_id %>
              <%= f.text_area :content,:id =>"query-text-area", :rows => "4", :cols =>"57", :placeholder=> "Ask a question or make a suggestion HERE." %>
              <br/>
              <%= f.submit "Query", :class => "button", :id => "submit_btn" %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

    <div id="about">
      <div id="menubar">
        <ul>
          <li><%= link_to image_tag "questionsa.jpg" %></li>
        </ul>
      </div>

     <div id="questions" class="comments">
       <% unless @questions.blank? -%>
       <% @questions.each do |question| -%>
         <div class="postedby"><p><%= link_to question.member.user_name unless question.member.blank?%></p></div>
         <div class="thumbimage"><%= image_tag question.member.avatar.url("small") unless question.member.blank?%></div>
         <div class="questiontext"><p><%=link_to question.content, community_question_path(question.community, question) %></p></div>
         <div class="time"><%="#{time_ago_in_words question.created_at} ago"  %></div>
            <div class="responses"><%= pluralize question.responses.count, "response" %></div>
            <div class="status"><%= question.status %></div>
            <hr/>
          <% end -%>
          <% end -%>
        </div> 

      <%#pagination functionality for questions displayed%> 
      <%= will_paginate @questions %>

      <div id="menubar">
        <ul>
          <li><%= link_to image_tag "suggestionsa.jpg" %></li>
        </ul>
      </div>

     <div class="comments" id="suggestions">
       <% unless @suggestions.blank? -%>
       <% @suggestions.each do |suggestion| -%>
         <div class="postedby"><p><%= link_to suggestion.member.user_name unless suggestion.member.blank?%></p></div>
         <div class="thumbimage"><%= image_tag suggestion.member.avatar.url("small") unless suggestion.member.blank?%></div>
            
            
         <div class="suggestiontext"><p><%=link_to suggestion.content, community_suggestion_path(suggestion.community, suggestion) %></p></div>
         <div class="time"><%= "#{time_ago_in_words suggestion.created_at} ago"  %></div>
            <div class="responses"><%= pluralize suggestion.responses.count, "response" %></div>
            <div class="status"><%= suggestion.status %></div>
            <hr/>
          <% end -%>
          <% end -%>
        </div> 

    </div>
  </div>
  <!-- end #content -->
  <div id="sidebar">
    <ul>
      <li>
        <h2><%= "About #{@community.name}" %></h2>
        <hr/>
        <p>This is one of many support communities on
          GimmeSupport, a place where customers and companies connect around the products and services they use..</p>
        <p>
          <%= @community.description %>
        </p>
      </li>
      <li>
        <h2>About this Community</h2>
        <hr/>
        <span class="stats" id="community-questions-count">
          <%="#{pluralize(@questions.count, 'question')} posted"  %>
        </span>
        <br/>
        <span class="stats" id="community-suggestions-count">
          <%="#{pluralize(@suggestions.count, 'suggestion')} posted"  %>
        </span>
        <br/>
        <span class="stats" id="community-members-count">
          <%="#{ pluralize(@members.count, 'member')} on board" %>
        </span>
      </li>

      <li>
        <h2>User Stats</h2>
        <hr/>
        <%= image_tag Member.last.avatar.url("thumb") %>
        <br/>
        <span class="stats" id="member-total-questions">
          <%= "#{pluralize(Member.last.questions.count, 'question')} posted overall" %>
        </span>
        <br/>
        <span class="stats" id="member-total-suggestions">
          <%= "#{pluralize(Member.last.suggestions.count, 'suggestion')} posted overall" %>
        </span>
        <br/>
        <span class="stats" id="member-total-questions-community">
          <%#find the number of questions member has contributed to a specific community%> 
          <%= "#{pluralize((Member.last.questions & @community.questions).count, "question")} on this community" %>
        </span>
        <br/>
        <span class="stats" id="member-total-suggestions-community">
          <%#find the number of questions member has contributed to a specific community%> 
          <%= "#{pluralize((Member.last.suggestions & @community.suggestions).count, "suggestion")} on this community" %>
        </span>
      </li>

    </ul>
  </div>
</div>

app/views/communities/showw.html.erb
<div id="page">

  <div id="content">
    <div class="post">

      <ul>
        <li><a href="javascript:disable_enable()">Ask a question</a></li>
        <li><a href="javascript:disable_enable()">Post a suggestion</a></li>
      </ul>

      <div id='contact-form'>
         <%#currently the first member of the community is doing all the questions. TODO: Change this behaviour%> 
         <%= form_for @community.questions.build(:member_id => Member.first.id), :remote => true do |f|%>

          <%= f.hidden_field :member_id %>
          <%= f.hidden_field :community_id %>
          <%= f.text_area :content,:rows => "4", :cols =>"57", :placeholder=> "Ask a question or make a suggestion HERE." %>
          <br/>
          <%= f.submit "Query", :class => "button", :id => "submit_btn" %>
          <% end %>
      </div>

      </div>

  <%#<%= will_paginate @questions %>

  <div id="questions">

    <%= image_tag "coms.jpg" %>

    <%= render @questions unless @questions.empty? %>

  </div>

  <%= will_paginate @questions %>

    </div>


  <!-- end #content -->
  <div id="sidebar">
    <ul>		
      <li>
        <h2>About Apple</h2>
        <hr/>
        <p>This is one of many support communities on 
          Get Satisfaction, a place where customers and companies connect around the products and services they use..</p>
        <p>
          <%= @community.description %>
        </p>
      </li>
      <li>
        <h2>About this Community</h2>
        <hr/>
        <span id="community-questions-count">
        <%= pluralize(@questions.count, "question") %>
        </span>
        <br/>
        <span id="community-members-count">
        <%= pluralize(@members.count, "member") %>
        </span>
        <p>
          <%= @community.description %>
        </p>
        <p>This is one of many support communities on 
          Get Satisfaction, a place where customers and companies connect around the products and services they use..</p>
      </li>

      <li>
        <h2>User Stats</h2>
        <hr/>
        
        <span id="member-total-questions">
          <%= pluralize(Member.last.questions.count, "question") %>
        </span>
        <br/>
        <span id="member-total-questions-community">
           <%#find the number of questions member has contributed to a specific community%> 
          <%= pluralize((Member.last.questions & @community.questions).count, "question") %>
        </span>

        <p>This is one of many support communities on 
          Get Satisfaction, a place where customers and companies connect around the products and services they use..</p>
      </li>

    </ul>
  </div>
  <!-- end #sidebar -->
  <div style="clear: both;">&nbsp;</div>
</div>